name = "futures-risk-calculator"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

[build]
command = ""

# Uncomment and update when you're ready to use a custom domain
# routes = [
#   { pattern = "calculator.yourdomain.com", custom_domain = true }
# ]